FROM nvcr.io/nvidia/pytorch:25.01-py3

# Define environments
ENV MAX_JOBS=64

RUN apt-get update && \
    apt-get install -y aria2 libfreeimage3 libfreeimage-dev zlib1g

RUN pip install ninja ray[default]

# 1. Install FlashInfer
RUN git clone -b v0.2.2.post1 https://github.com/flashinfer-ai/flashinfer.git --recursive && \
    cd flashinfer && \
    pip install --no-build-isolation --verbose --editable .

# 2. Install vLLM
RUN git clone -b v0.8.3 https://github.com/vllm-project/vllm.git && \
    cd vllm && \
    python use_existing_torch.py && \
    pip install -r requirements/build.txt

RUN cd vllm && pip install -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple -r requirements/common.txt
RUN cd vllm && pip install -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple -r requirements/cuda.txt

RUN cd vllm && \
    MAX_JOBS=32 && pip install -e . --no-build-isolation

# 4. Install Sglang
RUN git clone -b v0.4.5.post3 https://github.com/sgl-project/sglang.git && \
    cd sglang && \
    pip install --no-deps -e "python[all]"

# 3. Install Extra
RUN pip install -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple torchdata \
    "transformers[hf_xet]>=4.51.0" accelerate datasets peft hf-transfer \
    "numpy<2.0.0" "pyarrow>=15.0.0" pandas \
    ray[default] codetiming hydra-core pylatexenc qwen-vl-utils wandb dill pybind11 liger-kernel mathruler \
    pytest py-spy pre-commit ruff

# 5. Install cudnn
RUN aria2c --max-tries=99999 https://developer.download.nvidia.com/compute/cudnn/9.8.0/local_installers/cudnn-local-repo-ubuntu2204-9.8.0_1.0-1_amd64.deb

RUN dpkg -i cudnn-local-repo-ubuntu2204-9.8.0_1.0-1_amd64.deb && \
    cp /var/cudnn-local-repo-ubuntu2204-9.8.0/cudnn-*-keyring.gpg /usr/share/keyrings/ && \
    apt-get update && \
    apt-get -y install cudnn9-cuda-12 libcudnn9-dev-cuda-12 && \
    rm cudnn-local-repo-ubuntu2204-9.8.0_1.0-1_amd64.deb

RUN pip install -i https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple nvidia-cudnn-cu12

# 6. Install Apex
RUN git clone https://github.com/NVIDIA/apex.git && \
    cd apex && \
    pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext" ./

# 7. Install TransformerEngine
RUN git clone -b v2.2 https://github.com/NVIDIA/TransformerEngine.git --recurse-submodules && \
    cd TransformerEngine && \
    export NVTE_FRAMEWORK=pytorch && \
    pip3 install --no-deps -e . --verbose

# 8. Install Megatron-LM
RUN git clone -b core_r0.12.0 https://github.com/NVIDIA/Megatron-LM.git && \
    cd Megatron-LM && \
    pip3 install --no-deps -e . --verbose

# 9. Fix torch triton bug
RUN pip install triton==3.1.0